In [1]:
import pandas as pd

df = pd.read_csv("popular.csv")

In [6]:
len(df[df["job_size"] > 2e5])

2542

In [2]:
df.describe()

arrival_time      job_size     ceiledcpu  ceiledmemory
count  6.890942e+07  6.890942e+07  6.890942e+07  6.890942e+07
mean   1.267765e+06  3.105614e+02  4.215497e-03  5.055868e-03
std    7.840097e+05  8.105388e+03  3.585523e-03  2.513254e-03
min    6.001701e+02  1.000000e-06  1.000000e-03  2.000000e-03
25%    5.779063e+05  4.955446e+01  2.000000e-03  2.000000e-03
50%    1.255278e+06  8.027975e+01  3.000000e-03  6.000000e-03
75%    1.937091e+06  1.692569e+02  7.000000e-03  6.000000e-03
max    2.678906e+06  2.678140e+06  1.600000e-02  1.200000e-02

In [12]:
import numpy as np

stats = df.groupby(["ceiledcpu", "ceiledmemory"]).size()
stats = pd.concat([stats, df.groupby(["ceiledcpu", "ceiledmemory"]).mean()["job_size"]], axis=1)
# stats["lambda"] = stats["count"] / df["arrival_time"].max()

In [13]:
df.groupby(["ceiledcpu", "ceiledmemory"]).mean()["job_size"]

ceiledcpu  ceiledmemory
0.001      0.006             79.133682
0.002      0.002            247.765460
           0.003            547.745443
           0.006            113.980439
0.003      0.002            539.416729
           0.006            272.089997
0.004      0.006            403.951718
0.005      0.006            411.556814
0.007      0.006            116.915775
0.016      0.012           1248.086930
Name: job_size, dtype: float64

In [16]:
stats

ceiledcpu  ceiledmemory
0.001      0.006            3909590
0.002      0.002           15843234
           0.003            4564673
           0.006            8924386
0.003      0.002            3251734
           0.006            6231739
0.004      0.006            4669357
0.005      0.006            3669487
0.007      0.006           13676162
0.016      0.012            4169055
dtype: int64

0     job_size
ceiledcpu ceiledmemory                       
0.001     0.006          3909590    79.133682
0.002     0.002         15843234   247.765460
          0.003          4564673   547.745443
          0.006          8924386   113.980439
0.003     0.002          3251734   539.416729
          0.006          6231739   272.089997
0.004     0.006          4669357   403.951718
0.005     0.006          3669487   411.556814
0.007     0.006         13676162   116.915775
0.016     0.012          4169055  1248.086930

In [3]:
D = np.concatenate((np.array([stats["ceiledcpu"]]).T, np.array([stats["ceiledmemory"]]).T), axis=1)
R = D.shape[1]
C = np.ones(R)
lmb = np.array(stats["lambda"])

In [4]:
from maxmin import get_candidates

alpha, candidates = get_candidates(C, D, lmb)
print(alpha)
print(candidates)
print(alpha @ candidates)
print(C, candidates @ D)


[[2.72042415e-01 1.23339968e-01 5.62025826e-03 1.31202669e-02
  1.61362359e-01 1.09702210e-01 5.81412172e-02 2.56628728e-01
  1.61145478e-05 2.64645591e-05]]
[[ 22.   0.   0.  18.  23.   0.  40.   1.   0.  39.]
 [  2.  26.  10.   0.  24.  71.   1.   0.  49.  11.]
 [  0.  68.   0.   0.   0.  36.   0.   0. 108.   0.]
 [  0.   2.   0.   0.   0.   0. 166.   0.   0.   0.]
 [  0.   2.   0. 125.   0.   0.   0.   0.  41.   0.]
 [  1.   2.  88.   5.   0.   4.   2.  93.  17.   0.]
 [  0.   0.  38.   0.   2. 146.   0.   1.   0.   0.]
 [ 19. 161.   0.   0.   0.   0.   0.   0.  94.   0.]
 [  0.   0. 333.   0.   0.   0.   0.   0.   0.   0.]
 [166.   2.   0.   0.   0.   0.   0.   0.   0.   0.]]
[[11.22165421 45.47466449 13.10192654 25.61556934  9.3334172  17.88689356
  13.40240528 10.53248915 39.25454099 11.96639382]]
[1. 1.] [[0.916 1.   ]
 [0.882 1.   ]
 [1.    1.   ]
 [0.668 1.   ]
 [0.541 1.   ]
 [0.795 1.   ]
 [0.525 1.   ]
 [0.999 1.   ]
 [0.666 0.999]
 [0.17  1.   ]]


In [6]:
alpha, candidates = get_candidates(C, D, lmb, verbose=True)

Set parameter Username
Set parameter LicenseID to value 2608571
Academic license - for non-commercial use only - expires 2026-01-11
Gurobi Optimizer version 12.0.0 build v12.0.0rc1 (linux64 - "Red Hat Enterprise Linux 8.10 (Ootpa)")

CPU model: Intel(R) Xeon(R) Gold 5120 CPU @ 2.20GHz, instruction set [SSE2|AVX|AVX2|AVX512]
Thread count: 28 physical cores, 56 logical processors, using up to 28 threads

Optimize a model with 131 rows, 111 columns and 320 nonzeros
Model fingerprint: 0xf5c3b5ff
Model has 20 quadratic constraints
Variable types: 11 continuous, 100 integer (0 binary)
Coefficient statistics:
  Matrix range     [1e-03, 1e+00]
  QMatrix range    [1e+00, 1e+00]
  QLMatrix range   [1e+00, 6e+00]
  Objective range  [1e+00, 1e+00]
  Bounds range     [0e+00, 0e+00]
  RHS range        [1e+00, 1e+00]
  QRHS range       [1e+00, 6e+00]
Presolve added 0 rows and 10 columns
Presolve removed 100 rows and 0 columns
Presolve time: 0.00s
Presolved: 241 rows, 222 columns, 740 nonzeros
Presolv

In [8]:
lmb, D

(array([1.45939797, 5.91406861, 1.70393174, 3.33135464, 1.21382907,
        2.32622532, 1.74300889, 1.36977071, 5.10512945, 1.5562528 ]),
 array([[0.001, 0.006],
        [0.002, 0.002],
        [0.002, 0.003],
        [0.002, 0.006],
        [0.003, 0.002],
        [0.003, 0.006],
        [0.004, 0.006],
        [0.005, 0.006],
        [0.007, 0.006],
        [0.016, 0.012]]))